#
# usage: mysql> source build.sql;
#

DROP DATABASE IF EXISTS blog;
CREATE DATABASE blog;
USE blog;
# id: 17 = 2015-01-02-123859
CREATE TABLE entry (id CHAR(17) PRIMARY KEY, title VARCHAR(200) NOT NULL, date DATE NOT NULL, body TEXT NOT NULL);

LOAD DATA LOCAL INFILE 'entry.csv' INTO TABLE entry FIELDS TERMINATED BY ',';

SELECT * FROM entry;
